# Generated by Django 4.2.6 on 2023-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('type_board', models.CharField(choices=[('Boardercross', 'Boardercross'), ('Slalom', 'Slalom'), ('Half-Pipe', 'Half-Pipe'), ('Slopestyle', 'Slopestyle'), ('Freeride', 'Freeride')], max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('name_of_board', models.CharField(max_length=100)),
            ],
        ),
    ]
